services:
  - type: web
    name: ratte
    runtime: python
    repo: https://github.com/titamoto/ratte.git
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && npm install --prefix client && npm run build --prefix client
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: DATABASE_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.8.13
